### PR TITLE
Add 252 Scheme to standard rounds

### PR DESCRIPTION
**Pull request by tabashir**
Hi @crobertsbmw .
This PR is to add the 252 scheme training rounds to the list that is available on the app. I know they are not an official round but a lot of clubs in the UK do this scheme in one form or another.
When we get new club members, invariably they start doing the 252 and most then ask me how to set it up in the app, so would be a lot easier if they are available from the get-go.
There is one extra feature in this PR where I found to get it building, I was initially getting a ReflectionCache error which seemed to be fixed by bumping the version of Gradle. You may not need or desire this even if you want the main part of the PR.
Wasn't sure if this was the correct repo to fire PRs to. I could see the original repo is marked as no longer in maintenance and I could see you had been doing most of the translations work. Please let me know if this is the wrong place!

### CODE REVIEW

**Comment by guyandtheworld** [comment]
Hi @tabashir! Appreciate your contribution to the repository. This is the right repo. Will merge this PR soon after taking it out for a test-run. We're planning a lot of things for MyTargets so if you have any ideas or enhancements we should make, let us know!

Best.

**Comment by tabashir** [comment]
Hi @guyandtheworld ,
As it happens, the original reason I'd forked the repo was that I was planning on adding handicap calculation to the summary page. Last time I did android development was a looooong time ago (HTC Desire was the flagship phone at the time!) so I thought I'd add the 252 stuff as a gentle warm-up to get a feel around Android Studio and the project itself.
Is this something that had been planned already?
Cheers,
Jez.

**Comment by guyandtheworld** [comment]
Not really. I'm relatively new to Android Studio too hahaha... We only recently started the work reviving MyTargets but I think it would be a good idea to add this handicap calculation as an issue so that we could take it up and solve it in the future, but if you're interested in adding it as a feature, we'd be pumped to have it.

Best.

**Comment by tabashir** [comment]
Sure thing. Wasn't really sure what was happening on the project. When I can get my head around the handicap calculations, I'll attempt adding it as a feature. Is there a new issue tracker or are you using the old one on original repo?

**Comment by guyandtheworld** [comment]
Whoops, I was under the impression that forks had issue trackers too hahaha... Adding it to the original repository would be fine. I tested out this PR, gonna merge it now. Appreciate your contribution!

**Pull request merged**
