### PR TITLE
Handicap Calculator

### PR DESCRIPTION
**Pull request by tabashir**
Hi folks,
This PR implements the handicap calculations that were previously discussed. I've not linked it to an issue as one does not exist and the original repo is closed so cannot create new issues there.
This calculates the handicap as per David Lane's formulae. It will display this in the stats page of the round. It will also give you the handicap of each distance shot during that round so you can see which ones you performed better on.

Selection_204

I've had to rework the stats view a little - you can now see I've put the Hits and Average (Ø) on separate line and added the handicap on the end of that line denoted by a sigma (∑). Not sure that sigma is the correct icon for this but can't think what else would be a good one and sigma features a lot in the integration formulae. A staircase would be ideal but can't find one of them as a UTF8 character.

Happy to change anything that doesn't make sense though.

All of the calculation functions are covered with tests I think (I hope!!). A lot of the test cases have multiple assertions. This is down to the fact that rounding issues can easily skew a handicap by a point on the boundaries. Rather than have a mass of boiler plate that sets up the same test data a bunch of times, I used multiple assertions instead. Entirely possible there are some other boundary issues I haven't discovered yet, but I did to a fair amount of table comparison that wasn't worth putting into extra tests as that may just make refactoring more onerous later down the line.

### CODE REVIEW

**Comment by guyandtheworld** [comment]
Hey! Thanks for contributing. @crobertsbmw will enable the issue tracker soon. Reviewing this now.

**Comment by guyandtheworld** [comment]
So I might need your help here to digest this code. My experience with Archery is limited, so please bear with the questions, so is this calculated automatically during every shot? I'll do some reading on the handicap calculations.

**Comment by guyandtheworld** [comment]
@tabashir I might need your help here to digest this code. My experience with Archery is limited, so please bear with the questions, so is this calculated automatically during every shot and displayed in the stats screen? No disruption to the user-flow, yes? I'll do some reading on the handicap calculations.

**Comment by tabashir** [comment]
Hi,

Thanks for the reply.

It will re-calculate every time they go to the stats screen. However, as it
stands, it is only truly accurate at the end of the round. This is because
it calculates the handicap based on the total number of arrows that will be
shot in that round rather than the number of arrows that have currently
been shot. As it stands, I think from the people I know that use the app, I
don't know any that check stats mid-round, rather they stay in the scoring
screens until done then only go to the stats screen to view and share
results after.

I could change it to show progress during a round and actually think that
would be a good (and unique to MT) feature but it isn't how handicaps are
currently used by anyone, so I'd like to get it out there in 'standard'
form and see how that goes before adding more complexity in there.

There is definitely value in tracking and calculating handicaps during a
round as it gives a better indicator than average score when you have
sub-rounds at different distances making up a full round.

Hope this helps, please don't hesitate to give me a yell if you need more
info.

**Comment by tabashir** [comment]
On your other question, there is no disruption to the current user flow. I suspect most users won't even notice the functionality until they see the sigma box and wonder what it is!

Also, I believe that this gives a fairly unique functionality in that it calculates handicaps using the standard formula but is based on the dimensions and distances set in the round. This means that you can calculate what a handicap would be for any given target at any given distance, not just the 'standard' rounds where tables are published. This allows the archer to see how well they are progressing when they are shooting rounds like 252's or if they've just swapped to a longer distance.

I have a couple more features I'd like to add but will await the issue tracker being opened.

**Comment by tabashir** [comment]
I've just added an extra commit that adjusts for arrow diameter. I'd done the calculations based on this but hadn't passed in when showing the scoreboard. The default is a mid-range arrow size so it would likely have been unnoticed anyway by a lot of users, however, I do like things to work correctly!
This is now fixed. You can see this by editing your arrow and changing the diameter. Bear in mind that depending on the score, range and target size, you may not see a handicap change over the entire range of legal arrow widths. The screenshot attached, I took the previous round in the screenshot above and set the arrow to a really large diameter that they don't even make, simply to demonstrate the point.
Selection_205

**Comment by tabashir** [comment]
Also note that I've updated the help page with info on the handicaps etc. Please do take a look and suggest changes. Also need some translations ideally!

**Comment by guyandtheworld** [comment]
Thanks, @tabashir! I get the gist now. The issue tracker is open so you can go ahead and open issues for the features you want to see. I'm looking at the PR once more. Let me know if there's anything else you need.

**Comment by guyandtheworld** [comment]
Looking great! Merging PR.

**Comment by tabashir** [comment]
That's great @guyandtheworld . One of the features I already did - that was sorting out the calculation changing with different arrow diameters. However, have thought of an extra one so will raise issues and hopefully give you some more code for them soon :)
Any ideas when we'll see a new build pushed to the store?

**Comment by guyandtheworld** [comment]
@tabashir So we've been testing a new rollout with MyTargets and we're making sure that it's stable. Once that's done, I'll have all the new features in that! It should be live in a week or two.

**Comment by tabashir** [comment]
That's great @guyandtheworld . Thanks for getting this moving again.

**Comment by guyandtheworld** [comment]
@tabashir Rolled out the new features today! 🥳

**Comment by guyandtheworld** [comment]
Hey again, @tabashir.

On production, this error came up.

```
java.lang.RuntimeException: 
  at androidx.loader.content.ModernAsyncTask$3.done (ModernAsyncTask.java:164)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
Caused by: kotlin.KotlinNullPointerException: 
  at de.dreier.mytargets.shared.models.HandicapCalculator.<init> (HandicapCalculator.java:31)
  at de.dreier.mytargets.shared.models.MultiRoundHandicapCalculator.<init> (MultiRoundHandicapCalculator.java:27)
  at de.dreier.mytargets.features.scoreboard.layout.DefaultScoreboardLayout.getStatisticsForRound (DefaultScoreboardLayout.java:258)
  at de.dreier.mytargets.features.scoreboard.layout.DefaultScoreboardLayout.appendStatistics (DefaultScoreboardLayout.java:186)
  at de.dreier.mytargets.features.scoreboard.layout.DefaultScoreboardLayout.generateWithBuilder (DefaultScoreboardLayout.java:93)
  at de.dreier.mytargets.features.scoreboard.ScoreboardUtils.getScoreboardView (ScoreboardUtils.java:53)
  at de.dreier.mytargets.features.scoreboard.ScoreboardFragment.onLoad (ScoreboardFragment.java:133)
  at de.dreier.mytargets.base.fragments.FragmentBase$onCreateLoader$1.loadInBackground (FragmentBase.java:50)
  at de.dreier.mytargets.base.fragments.FragmentBase$onCreateLoader$1.loadInBackground (FragmentBase.java:48)
  at androidx.loader.content.AsyncTaskLoader.onLoadInBackground (AsyncTaskLoader.java:307)
  at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground (AsyncTaskLoader.java:60)
  at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground (AsyncTaskLoader.java:48)
  at androidx.loader.content.ModernAsyncTask$2.call (ModernAsyncTask.java:141)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
```

On a Samsung Galaxy A30s, Android 10 (SDK 29). Digging into this right now. Any ideas?

**Comment by tabashir** [comment]
How do you reproduce? Is it a totally empty round (ie, no ends shot?)

**Comment by tabashir** [comment]
I'm having issues installing it from the store at the moment. It's still reporting having the old version on there and no updates. I can see it if I go to the browser version of the store, but when I pushed the install, it still kept the old version. I've left the beta program to see if that made a difference but not so far.

**Comment by tabashir** [comment]
I have just tried empty round on the debug version and still do not see error. Looking at the line the code goes wrong, I think it could be down to the round in question not being set up with either a number of shots/end or max end count. I suspect that it is down to the max end count not being set up. I thought both of those needed to be set, but then I just thought of the 'free training' option that I have never used.... Just tried it and I think that may be the issue.

**Comment by guyandtheworld** [comment]
We were rolling the new update to only 10% of the users and maybe that's why you didn't get the update. Let me update the app with the patch and let me see if it fixes it.

**Pull request merged**
